name: Windows ray-tracing(C++) CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake & Ninja
        run: choco install cmake ninja -y

      - name: Configure CMake
        run: cmake -B build -G "Ninja"

      - name: Build Project
        run: cmake --build build

      - name: Run Tests
        run: |
          build/rayTracingTests
